dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

addons:
  apt:
    packages:
    - jpegoptim
    - pngquant
    - gifsicle
    - optipng

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - npm install -g svgo

install:
  - travis_retry composer self-update && composer --version
  - travis_retry phpunit --version
  - travis_retry composer global require "hirak/prestissimo:^0.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit --verbose
